apiVersion: batch/v1
kind: Job
metadata:
  name: dbimport
spec:
  template:
    metadata:
      name: dbimport
    spec:
      containers:
      - name: dbimport
        image: hellof20/p-azero:v1
        command: ["/azerothcore/env/dist/bin/dbimport"]
        volumeMounts:
        - name: config
          mountPath: /azerothcore/env/dist/etc/dbimport.conf
          subPath: dbimport.conf
          readOnly: true
      restartPolicy: Never          
      volumes:
      - name: config
        configMap:
          name: dbimport-configmap    


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbimport-configmap
data:
  dbimport.conf: |-
    LogsDir = "/azerothcore/env/dist/logs"
    SourceDirectory = ""
    MySQLExecutable = ""
    TempDir = ""
    LoginDatabaseInfo = "ac-database;3306;root;password;acore_auth"
    WorldDatabaseInfo = "ac-database;3306;root;password;acore_world"
    CharacterDatabaseInfo = "ac-database;3306;root;password;acore_characters"
    Database.Reconnect.Seconds = 5
    Database.Reconnect.Attempts = 5
    LoginDatabase.WorkerThreads     = 1
    WorldDatabase.WorkerThreads     = 1
    CharacterDatabase.WorkerThreads = 1
    LoginDatabase.SynchThreads     = 1
    WorldDatabase.SynchThreads     = 1
    CharacterDatabase.SynchThreads = 1
    Updates.EnableDatabases = 7
    Updates.AutoSetup = 1
    Updates.Redundancy = 1
    Updates.ArchivedRedundancy = 0
    Updates.AllowRehash = 1
    Updates.CleanDeadRefMaxCount = 3
    Appender.Console=1,5,0,"1 9 3 6 5 8"
    Appender.DBImport=2,5,0,DBImport.log,w
    Logger.root=4,Console DBImport
    DataDir = "/azerothcore/env/dist/data"
    CloseIdleConnections = 0